# Generated by Django 4.2 on 2025-12-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="samplemodel",
            old_name="number",
            new_name="image",
        ),
    ]
