# Generated by Django 4.2 on 2025-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_number_samplemodel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("text", models.TextField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("django", "Django"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SampleModel",
        ),
    ]
